#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("b1_req_din", 1, hls_out, 0, "ap_bus", "fifo_data", 1),
	Port_Property("b1_req_full_n", 1, hls_in, 0, "ap_bus", "fifo_status", 1),
	Port_Property("b1_req_write", 1, hls_out, 0, "ap_bus", "fifo_update", 1),
	Port_Property("b1_rsp_empty_n", 1, hls_in, 0, "ap_bus", "fifo_status", 1),
	Port_Property("b1_rsp_read", 1, hls_out, 0, "ap_bus", "fifo_update", 1),
	Port_Property("b1_address", 32, hls_out, 0, "ap_bus", "unknown", 1),
	Port_Property("b1_datain", 256, hls_in, 0, "ap_bus", "unknown", 1),
	Port_Property("b1_dataout", 256, hls_out, 0, "ap_bus", "unknown", 1),
	Port_Property("b1_size", 32, hls_out, 0, "ap_bus", "unknown", 1),
	Port_Property("b2_req_din", 1, hls_out, 1, "ap_bus", "fifo_data", 1),
	Port_Property("b2_req_full_n", 1, hls_in, 1, "ap_bus", "fifo_status", 1),
	Port_Property("b2_req_write", 1, hls_out, 1, "ap_bus", "fifo_update", 1),
	Port_Property("b2_rsp_empty_n", 1, hls_in, 1, "ap_bus", "fifo_status", 1),
	Port_Property("b2_rsp_read", 1, hls_out, 1, "ap_bus", "fifo_update", 1),
	Port_Property("b2_address", 32, hls_out, 1, "ap_bus", "unknown", 1),
	Port_Property("b2_datain", 256, hls_in, 1, "ap_bus", "unknown", 1),
	Port_Property("b2_dataout", 256, hls_out, 1, "ap_bus", "unknown", 1),
	Port_Property("b2_size", 32, hls_out, 1, "ap_bus", "unknown", 1),
	Port_Property("b3_req_din", 1, hls_out, 2, "ap_bus", "fifo_data", 1),
	Port_Property("b3_req_full_n", 1, hls_in, 2, "ap_bus", "fifo_status", 1),
	Port_Property("b3_req_write", 1, hls_out, 2, "ap_bus", "fifo_update", 1),
	Port_Property("b3_rsp_empty_n", 1, hls_in, 2, "ap_bus", "fifo_status", 1),
	Port_Property("b3_rsp_read", 1, hls_out, 2, "ap_bus", "fifo_update", 1),
	Port_Property("b3_address", 32, hls_out, 2, "ap_bus", "unknown", 1),
	Port_Property("b3_datain", 256, hls_in, 2, "ap_bus", "unknown", 1),
	Port_Property("b3_dataout", 256, hls_out, 2, "ap_bus", "unknown", 1),
	Port_Property("b3_size", 32, hls_out, 2, "ap_bus", "unknown", 1),
	Port_Property("blockSize", 32, hls_in, 3, "ap_hs", "in_data", 1),
	Port_Property("blockSize_ap_vld", 1, hls_in, 3, "ap_hs", "in_vld", 1),
	Port_Property("blockSize_ap_ack", 1, hls_out, 3, "ap_hs", "in_acc", 1),
};
const char* HLS_Design_Meta::dut_name = "bmm_top";
