// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xbmm_top.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XBmm_top_CfgInitialize(XBmm_top *InstancePtr, XBmm_top_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_BaseAddress = ConfigPtr->Control_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XBmm_top_Start(XBmm_top *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmm_top_ReadReg(InstancePtr->Control_BaseAddress, XBMM_TOP_CONTROL_ADDR_AP_CTRL) & 0x80;
    XBmm_top_WriteReg(InstancePtr->Control_BaseAddress, XBMM_TOP_CONTROL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XBmm_top_IsDone(XBmm_top *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmm_top_ReadReg(InstancePtr->Control_BaseAddress, XBMM_TOP_CONTROL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XBmm_top_IsIdle(XBmm_top *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmm_top_ReadReg(InstancePtr->Control_BaseAddress, XBMM_TOP_CONTROL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XBmm_top_IsReady(XBmm_top *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmm_top_ReadReg(InstancePtr->Control_BaseAddress, XBMM_TOP_CONTROL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XBmm_top_EnableAutoRestart(XBmm_top *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBmm_top_WriteReg(InstancePtr->Control_BaseAddress, XBMM_TOP_CONTROL_ADDR_AP_CTRL, 0x80);
}

void XBmm_top_DisableAutoRestart(XBmm_top *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBmm_top_WriteReg(InstancePtr->Control_BaseAddress, XBMM_TOP_CONTROL_ADDR_AP_CTRL, 0);
}

void XBmm_top_SetBlocksize(XBmm_top *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBmm_top_WriteReg(InstancePtr->Control_BaseAddress, XBMM_TOP_CONTROL_ADDR_BLOCKSIZE_DATA, Data);
}

u32 XBmm_top_GetBlocksize(XBmm_top *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmm_top_ReadReg(InstancePtr->Control_BaseAddress, XBMM_TOP_CONTROL_ADDR_BLOCKSIZE_DATA);
    return Data;
}

void XBmm_top_SetBlocksizeVld(XBmm_top *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBmm_top_WriteReg(InstancePtr->Control_BaseAddress, XBMM_TOP_CONTROL_ADDR_BLOCKSIZE_CTRL, 1);
}

u32 XBmm_top_GetBlocksizeVld(XBmm_top *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmm_top_ReadReg(InstancePtr->Control_BaseAddress, XBMM_TOP_CONTROL_ADDR_BLOCKSIZE_CTRL);
    return Data & 0x1;
}

u32 XBmm_top_GetBlocksizeAck(XBmm_top *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmm_top_ReadReg(InstancePtr->Control_BaseAddress, XBMM_TOP_CONTROL_ADDR_BLOCKSIZE_CTRL);
    return (Data >> 1) & 0x1;
}

void XBmm_top_InterruptGlobalEnable(XBmm_top *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBmm_top_WriteReg(InstancePtr->Control_BaseAddress, XBMM_TOP_CONTROL_ADDR_GIE, 1);
}

void XBmm_top_InterruptGlobalDisable(XBmm_top *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBmm_top_WriteReg(InstancePtr->Control_BaseAddress, XBMM_TOP_CONTROL_ADDR_GIE, 0);
}

void XBmm_top_InterruptEnable(XBmm_top *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XBmm_top_ReadReg(InstancePtr->Control_BaseAddress, XBMM_TOP_CONTROL_ADDR_IER);
    XBmm_top_WriteReg(InstancePtr->Control_BaseAddress, XBMM_TOP_CONTROL_ADDR_IER, Register | Mask);
}

void XBmm_top_InterruptDisable(XBmm_top *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XBmm_top_ReadReg(InstancePtr->Control_BaseAddress, XBMM_TOP_CONTROL_ADDR_IER);
    XBmm_top_WriteReg(InstancePtr->Control_BaseAddress, XBMM_TOP_CONTROL_ADDR_IER, Register & (~Mask));
}

void XBmm_top_InterruptClear(XBmm_top *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBmm_top_WriteReg(InstancePtr->Control_BaseAddress, XBMM_TOP_CONTROL_ADDR_ISR, Mask);
}

u32 XBmm_top_InterruptGetEnabled(XBmm_top *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XBmm_top_ReadReg(InstancePtr->Control_BaseAddress, XBMM_TOP_CONTROL_ADDR_IER);
}

u32 XBmm_top_InterruptGetStatus(XBmm_top *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XBmm_top_ReadReg(InstancePtr->Control_BaseAddress, XBMM_TOP_CONTROL_ADDR_ISR);
}

