// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xfe_top.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XFe_top_CfgInitialize(XFe_top *InstancePtr, XFe_top_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_BaseAddress = ConfigPtr->Control_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XFe_top_Start(XFe_top *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFe_top_ReadReg(InstancePtr->Control_BaseAddress, XFE_TOP_CONTROL_ADDR_AP_CTRL) & 0x80;
    XFe_top_WriteReg(InstancePtr->Control_BaseAddress, XFE_TOP_CONTROL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XFe_top_IsDone(XFe_top *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFe_top_ReadReg(InstancePtr->Control_BaseAddress, XFE_TOP_CONTROL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XFe_top_IsIdle(XFe_top *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFe_top_ReadReg(InstancePtr->Control_BaseAddress, XFE_TOP_CONTROL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XFe_top_IsReady(XFe_top *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFe_top_ReadReg(InstancePtr->Control_BaseAddress, XFE_TOP_CONTROL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XFe_top_EnableAutoRestart(XFe_top *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFe_top_WriteReg(InstancePtr->Control_BaseAddress, XFE_TOP_CONTROL_ADDR_AP_CTRL, 0x80);
}

void XFe_top_DisableAutoRestart(XFe_top *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFe_top_WriteReg(InstancePtr->Control_BaseAddress, XFE_TOP_CONTROL_ADDR_AP_CTRL, 0);
}

void XFe_top_InterruptGlobalEnable(XFe_top *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFe_top_WriteReg(InstancePtr->Control_BaseAddress, XFE_TOP_CONTROL_ADDR_GIE, 1);
}

void XFe_top_InterruptGlobalDisable(XFe_top *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFe_top_WriteReg(InstancePtr->Control_BaseAddress, XFE_TOP_CONTROL_ADDR_GIE, 0);
}

void XFe_top_InterruptEnable(XFe_top *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XFe_top_ReadReg(InstancePtr->Control_BaseAddress, XFE_TOP_CONTROL_ADDR_IER);
    XFe_top_WriteReg(InstancePtr->Control_BaseAddress, XFE_TOP_CONTROL_ADDR_IER, Register | Mask);
}

void XFe_top_InterruptDisable(XFe_top *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XFe_top_ReadReg(InstancePtr->Control_BaseAddress, XFE_TOP_CONTROL_ADDR_IER);
    XFe_top_WriteReg(InstancePtr->Control_BaseAddress, XFE_TOP_CONTROL_ADDR_IER, Register & (~Mask));
}

void XFe_top_InterruptClear(XFe_top *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFe_top_WriteReg(InstancePtr->Control_BaseAddress, XFE_TOP_CONTROL_ADDR_ISR, Mask);
}

u32 XFe_top_InterruptGetEnabled(XFe_top *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XFe_top_ReadReg(InstancePtr->Control_BaseAddress, XFE_TOP_CONTROL_ADDR_IER);
}

u32 XFe_top_InterruptGetStatus(XFe_top *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XFe_top_ReadReg(InstancePtr->Control_BaseAddress, XFE_TOP_CONTROL_ADDR_ISR);
}

