// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XSIMPLE_TOP_H
#define XSIMPLE_TOP_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xsimple_top_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_BaseAddress;
} XSimple_top_Config;
#endif

typedef struct {
    u32 Control_BaseAddress;
    u32 IsReady;
} XSimple_top;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XSimple_top_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XSimple_top_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XSimple_top_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XSimple_top_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XSimple_top_Initialize(XSimple_top *InstancePtr, u16 DeviceId);
XSimple_top_Config* XSimple_top_LookupConfig(u16 DeviceId);
int XSimple_top_CfgInitialize(XSimple_top *InstancePtr, XSimple_top_Config *ConfigPtr);
#else
int XSimple_top_Initialize(XSimple_top *InstancePtr, const char* InstanceName);
int XSimple_top_Release(XSimple_top *InstancePtr);
#endif

void XSimple_top_Start(XSimple_top *InstancePtr);
u32 XSimple_top_IsDone(XSimple_top *InstancePtr);
u32 XSimple_top_IsIdle(XSimple_top *InstancePtr);
u32 XSimple_top_IsReady(XSimple_top *InstancePtr);
void XSimple_top_EnableAutoRestart(XSimple_top *InstancePtr);
void XSimple_top_DisableAutoRestart(XSimple_top *InstancePtr);


void XSimple_top_InterruptGlobalEnable(XSimple_top *InstancePtr);
void XSimple_top_InterruptGlobalDisable(XSimple_top *InstancePtr);
void XSimple_top_InterruptEnable(XSimple_top *InstancePtr, u32 Mask);
void XSimple_top_InterruptDisable(XSimple_top *InstancePtr, u32 Mask);
void XSimple_top_InterruptClear(XSimple_top *InstancePtr, u32 Mask);
u32 XSimple_top_InterruptGetEnabled(XSimple_top *InstancePtr);
u32 XSimple_top_InterruptGetStatus(XSimple_top *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
