// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xbmm_top.h"

extern XBmm_top_Config XBmm_top_ConfigTable[];

XBmm_top_Config *XBmm_top_LookupConfig(u16 DeviceId) {
	XBmm_top_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XBMM_TOP_NUM_INSTANCES; Index++) {
		if (XBmm_top_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XBmm_top_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XBmm_top_Initialize(XBmm_top *InstancePtr, u16 DeviceId) {
	XBmm_top_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XBmm_top_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XBmm_top_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

