// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XBMM_TOP_H
#define XBMM_TOP_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xbmm_top_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_BaseAddress;
} XBmm_top_Config;
#endif

typedef struct {
    u32 Control_BaseAddress;
    u32 IsReady;
} XBmm_top;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XBmm_top_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XBmm_top_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XBmm_top_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XBmm_top_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XBmm_top_Initialize(XBmm_top *InstancePtr, u16 DeviceId);
XBmm_top_Config* XBmm_top_LookupConfig(u16 DeviceId);
int XBmm_top_CfgInitialize(XBmm_top *InstancePtr, XBmm_top_Config *ConfigPtr);
#else
int XBmm_top_Initialize(XBmm_top *InstancePtr, const char* InstanceName);
int XBmm_top_Release(XBmm_top *InstancePtr);
#endif

void XBmm_top_Start(XBmm_top *InstancePtr);
u32 XBmm_top_IsDone(XBmm_top *InstancePtr);
u32 XBmm_top_IsIdle(XBmm_top *InstancePtr);
u32 XBmm_top_IsReady(XBmm_top *InstancePtr);
void XBmm_top_EnableAutoRestart(XBmm_top *InstancePtr);
void XBmm_top_DisableAutoRestart(XBmm_top *InstancePtr);

void XBmm_top_SetOption(XBmm_top *InstancePtr, u32 Data);
u32 XBmm_top_GetOption(XBmm_top *InstancePtr);
void XBmm_top_SetOptionVld(XBmm_top *InstancePtr);
u32 XBmm_top_GetOptionVld(XBmm_top *InstancePtr);
u32 XBmm_top_GetOptionAck(XBmm_top *InstancePtr);

void XBmm_top_InterruptGlobalEnable(XBmm_top *InstancePtr);
void XBmm_top_InterruptGlobalDisable(XBmm_top *InstancePtr);
void XBmm_top_InterruptEnable(XBmm_top *InstancePtr, u32 Mask);
void XBmm_top_InterruptDisable(XBmm_top *InstancePtr, u32 Mask);
void XBmm_top_InterruptClear(XBmm_top *InstancePtr, u32 Mask);
u32 XBmm_top_InterruptGetEnabled(XBmm_top *InstancePtr);
u32 XBmm_top_InterruptGetStatus(XBmm_top *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
