
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 2013.3 EDK_P.20131013
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xbmm_top.h"

/*
* The configuration table for devices
*/

XBmm_top_Config XBmm_top_ConfigTable[] =
{
	{
		XPAR_BMM_TOP_0_DEVICE_ID,
		XPAR_BMM_TOP_0_S_AXI_CONTROL_BASEADDR
	},
	{
		XPAR_BMM_TOP_1_DEVICE_ID,
		XPAR_BMM_TOP_1_S_AXI_CONTROL_BASEADDR
	},
	{
		XPAR_BMM_TOP_2_DEVICE_ID,
		XPAR_BMM_TOP_2_S_AXI_CONTROL_BASEADDR
	},
	{
		XPAR_BMM_TOP_3_DEVICE_ID,
		XPAR_BMM_TOP_3_S_AXI_CONTROL_BASEADDR
	}
};


