# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1
set_property target_language Verilog [current_project]
set_property board em.avnet.com:zynq:zed:d [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property ip_repo_paths {
  /home/raghu/work/vivadoProjects/bmm/hls/simple_top/solution1/impl
  /home/raghu/work/vivadoProjects/bmm/hls/bmm_top/solution1/impl
  /home/raghu/work/vivadoProjects/bmm/hls/fe_top/solution1/impl
} [current_fileset]

add_files /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/dma3.bd
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_processing_system7_0_0/dma3_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_proc_sys_reset_1/dma3_proc_sys_reset_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_proc_sys_reset_1/dma3_proc_sys_reset_1.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_proc_sys_reset_1/dma3_proc_sys_reset_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_axi_cdma_0_0/dma3_axi_cdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_axi_cdma_0_0/dma3_axi_cdma_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_fe_top_0_0/constraints/fe_top_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_bmm_top_0_1/constraints/bmm_top_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_bmm_top_0_2/constraints/bmm_top_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_bram_ctrl_in_blk_10/dma3_bram_ctrl_in_blk_10_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_blk_mem_gen_inblk_12/dma3_blk_mem_gen_inblk_12_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_bram_ctrl_outblk_11/dma3_bram_ctrl_outblk_11_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_blk_mem_gen_outblk_13/dma3_blk_mem_gen_outblk_13_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_bmm_top_0_3/constraints/bmm_top_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_bram_ctrl_in_blk_13/dma3_bram_ctrl_in_blk_13_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_blk_mem_gen_inblk_15/dma3_blk_mem_gen_inblk_15_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_bram_ctrl_outblk_14/dma3_bram_ctrl_outblk_14_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_blk_mem_gen_outblk_16/dma3_blk_mem_gen_outblk_16_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_bmm_top_0_4/constraints/bmm_top_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_bram_ctrl_in_blk_15/dma3_bram_ctrl_in_blk_15_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_blk_mem_gen_inblk_17/dma3_blk_mem_gen_inblk_17_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_bram_ctrl_outblk_16/dma3_bram_ctrl_outblk_16_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_blk_mem_gen_outblk_18/dma3_blk_mem_gen_outblk_18_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_bram_ctrl_in_blk_17/dma3_bram_ctrl_in_blk_17_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_blk_mem_gen_inblk_19/dma3_blk_mem_gen_inblk_19_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_bram_ctrl_outblk_18/dma3_bram_ctrl_outblk_18_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_blk_mem_gen_outblk_20/dma3_blk_mem_gen_outblk_20_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_bram_ctrl_in_blk_19/dma3_bram_ctrl_in_blk_19_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_blk_mem_gen_inblk_21/dma3_blk_mem_gen_inblk_21_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_axi_dwidth_converter_0_1/dma3_axi_dwidth_converter_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_axi_dwidth_converter_0_1/dma3_axi_dwidth_converter_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_xbar_14/dma3_xbar_14_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_xbar_15/dma3_xbar_15_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_xbar_16/dma3_xbar_16_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_xbar_17/dma3_xbar_17_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_xbar_18/dma3_xbar_18_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_xbar_19/dma3_xbar_19_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_auto_pc_192/dma3_auto_pc_192_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_auto_pc_193/dma3_auto_pc_193_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_auto_pc_194/dma3_auto_pc_194_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_auto_us_50/dma3_auto_us_50_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_auto_us_50/dma3_auto_us_50_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_auto_us_51/dma3_auto_us_51_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_auto_us_51/dma3_auto_us_51_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_auto_us_52/dma3_auto_us_52_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_auto_us_52/dma3_auto_us_52_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_auto_us_53/dma3_auto_us_53_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_auto_us_53/dma3_auto_us_53_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_auto_us_54/dma3_auto_us_54_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_auto_us_54/dma3_auto_us_54_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_auto_us_55/dma3_auto_us_55_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_auto_us_55/dma3_auto_us_55_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_auto_us_56/dma3_auto_us_56_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_auto_us_56/dma3_auto_us_56_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_auto_us_57/dma3_auto_us_57_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_auto_us_57/dma3_auto_us_57_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_auto_us_58/dma3_auto_us_58_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_auto_us_58/dma3_auto_us_58_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_auto_us_59/dma3_auto_us_59_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_auto_us_59/dma3_auto_us_59_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_auto_us_60/dma3_auto_us_60_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_auto_us_60/dma3_auto_us_60_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_auto_us_61/dma3_auto_us_61_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/ip/dma3_auto_us_61/dma3_auto_us_61_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/dma3_ooc.xdc]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/dma3.bd]

read_verilog /home/raghu/work/vivadoProjects/bmm/dma3.srcs/sources_1/bd/dma3/hdl/dma3_wrapper.v
read_xdc /home/raghu/work/vivadoProjects/bmm/dma3.srcs/constrs_1/new/dma3_wrapper.xdc
set_property used_in_implementation false [get_files /home/raghu/work/vivadoProjects/bmm/dma3.srcs/constrs_1/new/dma3_wrapper.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/raghu/work/vivadoProjects/bmm/dma3.data/wt [current_project]
set_property parent.project_dir /home/raghu/work/vivadoProjects/bmm [current_project]
synth_design -top dma3_wrapper -part xc7z020clg484-1
write_checkpoint dma3_wrapper.dcp
report_utilization -file dma3_wrapper_utilization_synth.rpt -pb dma3_wrapper_utilization_synth.pb
