# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/dma3_wrapper.xdc

# Block Designs: bd/dma3/dma3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3 || ORIG_REF_NAME==dma3}]

# IP: bd/dma3/ip/dma3_processing_system7_0_0/dma3_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_processing_system7_0_0 || ORIG_REF_NAME==dma3_processing_system7_0_0}]

# IP: bd/dma3/ip/dma3_processing_system7_0_axi_periph_1/dma3_processing_system7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_processing_system7_0_axi_periph_1 || ORIG_REF_NAME==dma3_processing_system7_0_axi_periph_1}]

# IP: bd/dma3/ip/dma3_proc_sys_reset_1/dma3_proc_sys_reset_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_proc_sys_reset_1 || ORIG_REF_NAME==dma3_proc_sys_reset_1}]

# IP: bd/dma3/ip/dma3_axi_mem_intercon_2/dma3_axi_mem_intercon_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_axi_mem_intercon_2 || ORIG_REF_NAME==dma3_axi_mem_intercon_2}]

# IP: bd/dma3/ip/dma3_axi_cdma_0_0/dma3_axi_cdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_axi_cdma_0_0 || ORIG_REF_NAME==dma3_axi_cdma_0_0}]

# IP: bd/dma3/ip/dma3_xbar_1/dma3_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_xbar_1 || ORIG_REF_NAME==dma3_xbar_1}]

# IP: bd/dma3/ip/dma3_xbar_2/dma3_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_xbar_2 || ORIG_REF_NAME==dma3_xbar_2}]

# IP: bd/dma3/ip/dma3_fe_top_0_0/dma3_fe_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_fe_top_0_0 || ORIG_REF_NAME==dma3_fe_top_0_0}]

# IP: bd/dma3/ip/dma3_axi_mem_intercon_1_7/dma3_axi_mem_intercon_1_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_axi_mem_intercon_1_7 || ORIG_REF_NAME==dma3_axi_mem_intercon_1_7}]

# IP: bd/dma3/ip/dma3_bmm_top_0_1/dma3_bmm_top_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_bmm_top_0_1 || ORIG_REF_NAME==dma3_bmm_top_0_1}]

# IP: bd/dma3/ip/dma3_bmm_top_0_2/dma3_bmm_top_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_bmm_top_0_2 || ORIG_REF_NAME==dma3_bmm_top_0_2}]

# IP: bd/dma3/ip/dma3_bram_ctrl_in_blk_10/dma3_bram_ctrl_in_blk_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_bram_ctrl_in_blk_10 || ORIG_REF_NAME==dma3_bram_ctrl_in_blk_10}]

# IP: bd/dma3/ip/dma3_blk_mem_gen_inblk_12/dma3_blk_mem_gen_inblk_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_blk_mem_gen_inblk_12 || ORIG_REF_NAME==dma3_blk_mem_gen_inblk_12}]

# IP: bd/dma3/ip/dma3_bram_ctrl_outblk_11/dma3_bram_ctrl_outblk_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_bram_ctrl_outblk_11 || ORIG_REF_NAME==dma3_bram_ctrl_outblk_11}]

# IP: bd/dma3/ip/dma3_blk_mem_gen_outblk_13/dma3_blk_mem_gen_outblk_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_blk_mem_gen_outblk_13 || ORIG_REF_NAME==dma3_blk_mem_gen_outblk_13}]

# IP: bd/dma3/ip/dma3_bmm_top_0_3/dma3_bmm_top_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_bmm_top_0_3 || ORIG_REF_NAME==dma3_bmm_top_0_3}]

# IP: bd/dma3/ip/dma3_bram_ctrl_in_blk_13/dma3_bram_ctrl_in_blk_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_bram_ctrl_in_blk_13 || ORIG_REF_NAME==dma3_bram_ctrl_in_blk_13}]

# IP: bd/dma3/ip/dma3_blk_mem_gen_inblk_15/dma3_blk_mem_gen_inblk_15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_blk_mem_gen_inblk_15 || ORIG_REF_NAME==dma3_blk_mem_gen_inblk_15}]

# IP: bd/dma3/ip/dma3_bram_ctrl_outblk_14/dma3_bram_ctrl_outblk_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_bram_ctrl_outblk_14 || ORIG_REF_NAME==dma3_bram_ctrl_outblk_14}]

# IP: bd/dma3/ip/dma3_blk_mem_gen_outblk_16/dma3_blk_mem_gen_outblk_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_blk_mem_gen_outblk_16 || ORIG_REF_NAME==dma3_blk_mem_gen_outblk_16}]

# IP: bd/dma3/ip/dma3_bmm_top_0_4/dma3_bmm_top_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_bmm_top_0_4 || ORIG_REF_NAME==dma3_bmm_top_0_4}]

# IP: bd/dma3/ip/dma3_bram_ctrl_in_blk_15/dma3_bram_ctrl_in_blk_15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_bram_ctrl_in_blk_15 || ORIG_REF_NAME==dma3_bram_ctrl_in_blk_15}]

# IP: bd/dma3/ip/dma3_blk_mem_gen_inblk_17/dma3_blk_mem_gen_inblk_17.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_blk_mem_gen_inblk_17 || ORIG_REF_NAME==dma3_blk_mem_gen_inblk_17}]

# IP: bd/dma3/ip/dma3_bram_ctrl_outblk_16/dma3_bram_ctrl_outblk_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_bram_ctrl_outblk_16 || ORIG_REF_NAME==dma3_bram_ctrl_outblk_16}]

# IP: bd/dma3/ip/dma3_blk_mem_gen_outblk_18/dma3_blk_mem_gen_outblk_18.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_blk_mem_gen_outblk_18 || ORIG_REF_NAME==dma3_blk_mem_gen_outblk_18}]

# IP: bd/dma3/ip/dma3_bram_ctrl_in_blk_17/dma3_bram_ctrl_in_blk_17.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_bram_ctrl_in_blk_17 || ORIG_REF_NAME==dma3_bram_ctrl_in_blk_17}]

# IP: bd/dma3/ip/dma3_blk_mem_gen_inblk_19/dma3_blk_mem_gen_inblk_19.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_blk_mem_gen_inblk_19 || ORIG_REF_NAME==dma3_blk_mem_gen_inblk_19}]

# IP: bd/dma3/ip/dma3_bram_ctrl_outblk_18/dma3_bram_ctrl_outblk_18.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_bram_ctrl_outblk_18 || ORIG_REF_NAME==dma3_bram_ctrl_outblk_18}]

# IP: bd/dma3/ip/dma3_blk_mem_gen_outblk_20/dma3_blk_mem_gen_outblk_20.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_blk_mem_gen_outblk_20 || ORIG_REF_NAME==dma3_blk_mem_gen_outblk_20}]

# IP: bd/dma3/ip/dma3_bram_ctrl_in_blk_19/dma3_bram_ctrl_in_blk_19.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_bram_ctrl_in_blk_19 || ORIG_REF_NAME==dma3_bram_ctrl_in_blk_19}]

# IP: bd/dma3/ip/dma3_blk_mem_gen_inblk_21/dma3_blk_mem_gen_inblk_21.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_blk_mem_gen_inblk_21 || ORIG_REF_NAME==dma3_blk_mem_gen_inblk_21}]

# IP: bd/dma3/ip/dma3_axi_interconnect_0_12/dma3_axi_interconnect_0_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_axi_interconnect_0_12 || ORIG_REF_NAME==dma3_axi_interconnect_0_12}]

# IP: bd/dma3/ip/dma3_xbar_10/dma3_xbar_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_xbar_10 || ORIG_REF_NAME==dma3_xbar_10}]

# IP: bd/dma3/ip/dma3_axi_interconnect_0_13/dma3_axi_interconnect_0_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_axi_interconnect_0_13 || ORIG_REF_NAME==dma3_axi_interconnect_0_13}]

# IP: bd/dma3/ip/dma3_xbar_11/dma3_xbar_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_xbar_11 || ORIG_REF_NAME==dma3_xbar_11}]

# IP: bd/dma3/ip/dma3_axi_interconnect_0_14/dma3_axi_interconnect_0_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_axi_interconnect_0_14 || ORIG_REF_NAME==dma3_axi_interconnect_0_14}]

# IP: bd/dma3/ip/dma3_xbar_12/dma3_xbar_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_xbar_12 || ORIG_REF_NAME==dma3_xbar_12}]

# IP: bd/dma3/ip/dma3_axi_dwidth_converter_0_1/dma3_axi_dwidth_converter_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_axi_dwidth_converter_0_1 || ORIG_REF_NAME==dma3_axi_dwidth_converter_0_1}]

# IP: bd/dma3/ip/dma3_axi_interconnect_1_15/dma3_axi_interconnect_1_15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_axi_interconnect_1_15 || ORIG_REF_NAME==dma3_axi_interconnect_1_15}]

# IP: bd/dma3/ip/dma3_xbar_13/dma3_xbar_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_xbar_13 || ORIG_REF_NAME==dma3_xbar_13}]

# IP: bd/dma3/ip/dma3_auto_pc_183/dma3_auto_pc_183.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_auto_pc_183 || ORIG_REF_NAME==dma3_auto_pc_183}]

# IP: bd/dma3/ip/dma3_auto_pc_184/dma3_auto_pc_184.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_auto_pc_184 || ORIG_REF_NAME==dma3_auto_pc_184}]

# IP: bd/dma3/ip/dma3_auto_pc_185/dma3_auto_pc_185.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_auto_pc_185 || ORIG_REF_NAME==dma3_auto_pc_185}]

# IP: bd/dma3/ip/dma3_auto_us_14/dma3_auto_us_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_auto_us_14 || ORIG_REF_NAME==dma3_auto_us_14}]

# IP: bd/dma3/ip/dma3_auto_us_15/dma3_auto_us_15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_auto_us_15 || ORIG_REF_NAME==dma3_auto_us_15}]

# IP: bd/dma3/ip/dma3_auto_us_16/dma3_auto_us_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_auto_us_16 || ORIG_REF_NAME==dma3_auto_us_16}]

# IP: bd/dma3/ip/dma3_auto_us_17/dma3_auto_us_17.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_auto_us_17 || ORIG_REF_NAME==dma3_auto_us_17}]

# IP: bd/dma3/ip/dma3_auto_us_18/dma3_auto_us_18.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_auto_us_18 || ORIG_REF_NAME==dma3_auto_us_18}]

# IP: bd/dma3/ip/dma3_auto_us_19/dma3_auto_us_19.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_auto_us_19 || ORIG_REF_NAME==dma3_auto_us_19}]

# IP: bd/dma3/ip/dma3_auto_us_20/dma3_auto_us_20.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_auto_us_20 || ORIG_REF_NAME==dma3_auto_us_20}]

# IP: bd/dma3/ip/dma3_auto_us_21/dma3_auto_us_21.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_auto_us_21 || ORIG_REF_NAME==dma3_auto_us_21}]

# IP: bd/dma3/ip/dma3_auto_us_22/dma3_auto_us_22.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_auto_us_22 || ORIG_REF_NAME==dma3_auto_us_22}]

# IP: bd/dma3/ip/dma3_auto_us_23/dma3_auto_us_23.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_auto_us_23 || ORIG_REF_NAME==dma3_auto_us_23}]

# IP: bd/dma3/ip/dma3_auto_us_24/dma3_auto_us_24.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_auto_us_24 || ORIG_REF_NAME==dma3_auto_us_24}]

# IP: bd/dma3/ip/dma3_auto_us_25/dma3_auto_us_25.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_auto_us_25 || ORIG_REF_NAME==dma3_auto_us_25}]

# XDC: bd/dma3/ip/dma3_processing_system7_0_0/dma3_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma3_processing_system7_0_0 || ORIG_REF_NAME==dma3_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/dma3/ip/dma3_proc_sys_reset_1/dma3_proc_sys_reset_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma3_proc_sys_reset_1 || ORIG_REF_NAME==dma3_proc_sys_reset_1}] {/U0 }]/U0 ]]

# XDC: bd/dma3/ip/dma3_proc_sys_reset_1/dma3_proc_sys_reset_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma3_proc_sys_reset_1 || ORIG_REF_NAME==dma3_proc_sys_reset_1}] {/U0 }]/U0 ]]

# XDC: bd/dma3/ip/dma3_proc_sys_reset_1/dma3_proc_sys_reset_1_ooc.xdc

# XDC: bd/dma3/ip/dma3_axi_cdma_0_0/dma3_axi_cdma_0_0_ooc.xdc

# XDC: bd/dma3/ip/dma3_axi_cdma_0_0/dma3_axi_cdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma3_axi_cdma_0_0 || ORIG_REF_NAME==dma3_axi_cdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/dma3/ip/dma3_xbar_1/dma3_xbar_1_ooc.xdc

# XDC: bd/dma3/ip/dma3_xbar_2/dma3_xbar_2_ooc.xdc

# XDC: bd/dma3/ip/dma3_fe_top_0_0/constraints/fe_top_ooc.xdc

# XDC: bd/dma3/ip/dma3_bmm_top_0_1/constraints/bmm_top_ooc.xdc

# XDC: bd/dma3/ip/dma3_bmm_top_0_2/constraints/bmm_top_ooc.xdc

# XDC: bd/dma3/ip/dma3_bram_ctrl_in_blk_10/dma3_bram_ctrl_in_blk_10_ooc.xdc

# XDC: bd/dma3/ip/dma3_blk_mem_gen_inblk_12/dma3_blk_mem_gen_inblk_12_ooc.xdc

# XDC: bd/dma3/ip/dma3_bram_ctrl_outblk_11/dma3_bram_ctrl_outblk_11_ooc.xdc

# XDC: bd/dma3/ip/dma3_blk_mem_gen_outblk_13/dma3_blk_mem_gen_outblk_13_ooc.xdc

# XDC: bd/dma3/ip/dma3_bmm_top_0_3/constraints/bmm_top_ooc.xdc

# XDC: bd/dma3/ip/dma3_bram_ctrl_in_blk_13/dma3_bram_ctrl_in_blk_13_ooc.xdc

# XDC: bd/dma3/ip/dma3_blk_mem_gen_inblk_15/dma3_blk_mem_gen_inblk_15_ooc.xdc

# XDC: bd/dma3/ip/dma3_bram_ctrl_outblk_14/dma3_bram_ctrl_outblk_14_ooc.xdc

# XDC: bd/dma3/ip/dma3_blk_mem_gen_outblk_16/dma3_blk_mem_gen_outblk_16_ooc.xdc

# XDC: bd/dma3/ip/dma3_bmm_top_0_4/constraints/bmm_top_ooc.xdc

# XDC: bd/dma3/ip/dma3_bram_ctrl_in_blk_15/dma3_bram_ctrl_in_blk_15_ooc.xdc

# XDC: bd/dma3/ip/dma3_blk_mem_gen_inblk_17/dma3_blk_mem_gen_inblk_17_ooc.xdc

# XDC: bd/dma3/ip/dma3_bram_ctrl_outblk_16/dma3_bram_ctrl_outblk_16_ooc.xdc

# XDC: bd/dma3/ip/dma3_blk_mem_gen_outblk_18/dma3_blk_mem_gen_outblk_18_ooc.xdc

# XDC: bd/dma3/ip/dma3_bram_ctrl_in_blk_17/dma3_bram_ctrl_in_blk_17_ooc.xdc

# XDC: bd/dma3/ip/dma3_blk_mem_gen_inblk_19/dma3_blk_mem_gen_inblk_19_ooc.xdc

# XDC: bd/dma3/ip/dma3_bram_ctrl_outblk_18/dma3_bram_ctrl_outblk_18_ooc.xdc

# XDC: bd/dma3/ip/dma3_blk_mem_gen_outblk_20/dma3_blk_mem_gen_outblk_20_ooc.xdc

# XDC: bd/dma3/ip/dma3_bram_ctrl_in_blk_19/dma3_bram_ctrl_in_blk_19_ooc.xdc

# XDC: bd/dma3/ip/dma3_blk_mem_gen_inblk_21/dma3_blk_mem_gen_inblk_21_ooc.xdc

# XDC: bd/dma3/ip/dma3_xbar_10/dma3_xbar_10_ooc.xdc

# XDC: bd/dma3/ip/dma3_xbar_11/dma3_xbar_11_ooc.xdc

# XDC: bd/dma3/ip/dma3_xbar_12/dma3_xbar_12_ooc.xdc

# XDC: bd/dma3/ip/dma3_axi_dwidth_converter_0_1/dma3_axi_dwidth_converter_0_1_ooc.xdc

# XDC: bd/dma3/ip/dma3_axi_dwidth_converter_0_1/dma3_axi_dwidth_converter_0_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma3_axi_dwidth_converter_0_1 || ORIG_REF_NAME==dma3_axi_dwidth_converter_0_1}] {/inst }]/inst ]]

# XDC: bd/dma3/ip/dma3_xbar_13/dma3_xbar_13_ooc.xdc

# XDC: bd/dma3/ip/dma3_auto_pc_183/dma3_auto_pc_183_ooc.xdc

# XDC: bd/dma3/ip/dma3_auto_pc_184/dma3_auto_pc_184_ooc.xdc

# XDC: bd/dma3/ip/dma3_auto_pc_185/dma3_auto_pc_185_ooc.xdc

# XDC: bd/dma3/ip/dma3_auto_us_14/dma3_auto_us_14_ooc.xdc

# XDC: bd/dma3/ip/dma3_auto_us_14/dma3_auto_us_14_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma3_auto_us_14 || ORIG_REF_NAME==dma3_auto_us_14}] {/inst }]/inst ]]

# XDC: bd/dma3/ip/dma3_auto_us_15/dma3_auto_us_15_ooc.xdc

# XDC: bd/dma3/ip/dma3_auto_us_15/dma3_auto_us_15_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma3_auto_us_15 || ORIG_REF_NAME==dma3_auto_us_15}] {/inst }]/inst ]]

# XDC: bd/dma3/ip/dma3_auto_us_16/dma3_auto_us_16_ooc.xdc

# XDC: bd/dma3/ip/dma3_auto_us_16/dma3_auto_us_16_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma3_auto_us_16 || ORIG_REF_NAME==dma3_auto_us_16}] {/inst }]/inst ]]

# XDC: bd/dma3/ip/dma3_auto_us_17/dma3_auto_us_17_ooc.xdc

# XDC: bd/dma3/ip/dma3_auto_us_17/dma3_auto_us_17_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma3_auto_us_17 || ORIG_REF_NAME==dma3_auto_us_17}] {/inst }]/inst ]]

# XDC: bd/dma3/ip/dma3_auto_us_18/dma3_auto_us_18_ooc.xdc

# XDC: bd/dma3/ip/dma3_auto_us_18/dma3_auto_us_18_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma3_auto_us_18 || ORIG_REF_NAME==dma3_auto_us_18}] {/inst }]/inst ]]

# XDC: bd/dma3/ip/dma3_auto_us_19/dma3_auto_us_19_ooc.xdc

# XDC: bd/dma3/ip/dma3_auto_us_19/dma3_auto_us_19_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma3_auto_us_19 || ORIG_REF_NAME==dma3_auto_us_19}] {/inst }]/inst ]]

# XDC: bd/dma3/ip/dma3_auto_us_20/dma3_auto_us_20_ooc.xdc

# XDC: bd/dma3/ip/dma3_auto_us_20/dma3_auto_us_20_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma3_auto_us_20 || ORIG_REF_NAME==dma3_auto_us_20}] {/inst }]/inst ]]

# XDC: bd/dma3/ip/dma3_auto_us_21/dma3_auto_us_21_ooc.xdc

# XDC: bd/dma3/ip/dma3_auto_us_21/dma3_auto_us_21_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma3_auto_us_21 || ORIG_REF_NAME==dma3_auto_us_21}] {/inst }]/inst ]]

# XDC: bd/dma3/ip/dma3_auto_us_22/dma3_auto_us_22_ooc.xdc

# XDC: bd/dma3/ip/dma3_auto_us_22/dma3_auto_us_22_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma3_auto_us_22 || ORIG_REF_NAME==dma3_auto_us_22}] {/inst }]/inst ]]

# XDC: bd/dma3/ip/dma3_auto_us_23/dma3_auto_us_23_ooc.xdc

# XDC: bd/dma3/ip/dma3_auto_us_23/dma3_auto_us_23_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma3_auto_us_23 || ORIG_REF_NAME==dma3_auto_us_23}] {/inst }]/inst ]]

# XDC: bd/dma3/ip/dma3_auto_us_24/dma3_auto_us_24_ooc.xdc

# XDC: bd/dma3/ip/dma3_auto_us_24/dma3_auto_us_24_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma3_auto_us_24 || ORIG_REF_NAME==dma3_auto_us_24}] {/inst }]/inst ]]

# XDC: bd/dma3/ip/dma3_auto_us_25/dma3_auto_us_25_ooc.xdc

# XDC: bd/dma3/ip/dma3_auto_us_25/dma3_auto_us_25_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma3_auto_us_25 || ORIG_REF_NAME==dma3_auto_us_25}] {/inst }]/inst ]]

# XDC: bd/dma3/dma3_ooc.xdc
