# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/dma3_wrapper.xdc

# Block Designs: bd/dma3/dma3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3 || ORIG_REF_NAME==dma3}]

# IP: bd/dma3/ip/dma3_processing_system7_0_0/dma3_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_processing_system7_0_0 || ORIG_REF_NAME==dma3_processing_system7_0_0}]

# IP: bd/dma3/ip/dma3_processing_system7_0_axi_periph_1/dma3_processing_system7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_processing_system7_0_axi_periph_1 || ORIG_REF_NAME==dma3_processing_system7_0_axi_periph_1}]

# IP: bd/dma3/ip/dma3_proc_sys_reset_1/dma3_proc_sys_reset_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_proc_sys_reset_1 || ORIG_REF_NAME==dma3_proc_sys_reset_1}]

# IP: bd/dma3/ip/dma3_axi_mem_intercon_2/dma3_axi_mem_intercon_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_axi_mem_intercon_2 || ORIG_REF_NAME==dma3_axi_mem_intercon_2}]

# IP: bd/dma3/ip/dma3_axi_cdma_0_0/dma3_axi_cdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_axi_cdma_0_0 || ORIG_REF_NAME==dma3_axi_cdma_0_0}]

# IP: bd/dma3/ip/dma3_xbar_1/dma3_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_xbar_1 || ORIG_REF_NAME==dma3_xbar_1}]

# IP: bd/dma3/ip/dma3_xbar_2/dma3_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_xbar_2 || ORIG_REF_NAME==dma3_xbar_2}]

# IP: bd/dma3/ip/dma3_fe_top_0_0/dma3_fe_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_fe_top_0_0 || ORIG_REF_NAME==dma3_fe_top_0_0}]

# IP: bd/dma3/ip/dma3_axi_mem_intercon_1_7/dma3_axi_mem_intercon_1_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_axi_mem_intercon_1_7 || ORIG_REF_NAME==dma3_axi_mem_intercon_1_7}]

# IP: bd/dma3/ip/dma3_bmm_top_0_1/dma3_bmm_top_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_bmm_top_0_1 || ORIG_REF_NAME==dma3_bmm_top_0_1}]

# IP: bd/dma3/ip/dma3_bmm_top_0_2/dma3_bmm_top_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_bmm_top_0_2 || ORIG_REF_NAME==dma3_bmm_top_0_2}]

# IP: bd/dma3/ip/dma3_bram_ctrl_in_blk_10/dma3_bram_ctrl_in_blk_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_bram_ctrl_in_blk_10 || ORIG_REF_NAME==dma3_bram_ctrl_in_blk_10}]

# IP: bd/dma3/ip/dma3_blk_mem_gen_inblk_12/dma3_blk_mem_gen_inblk_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_blk_mem_gen_inblk_12 || ORIG_REF_NAME==dma3_blk_mem_gen_inblk_12}]

# IP: bd/dma3/ip/dma3_bram_ctrl_outblk_11/dma3_bram_ctrl_outblk_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_bram_ctrl_outblk_11 || ORIG_REF_NAME==dma3_bram_ctrl_outblk_11}]

# IP: bd/dma3/ip/dma3_blk_mem_gen_outblk_13/dma3_blk_mem_gen_outblk_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_blk_mem_gen_outblk_13 || ORIG_REF_NAME==dma3_blk_mem_gen_outblk_13}]

# IP: bd/dma3/ip/dma3_bmm_top_0_3/dma3_bmm_top_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_bmm_top_0_3 || ORIG_REF_NAME==dma3_bmm_top_0_3}]

# IP: bd/dma3/ip/dma3_bram_ctrl_in_blk_13/dma3_bram_ctrl_in_blk_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_bram_ctrl_in_blk_13 || ORIG_REF_NAME==dma3_bram_ctrl_in_blk_13}]

# IP: bd/dma3/ip/dma3_blk_mem_gen_inblk_15/dma3_blk_mem_gen_inblk_15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_blk_mem_gen_inblk_15 || ORIG_REF_NAME==dma3_blk_mem_gen_inblk_15}]

# IP: bd/dma3/ip/dma3_bram_ctrl_outblk_14/dma3_bram_ctrl_outblk_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_bram_ctrl_outblk_14 || ORIG_REF_NAME==dma3_bram_ctrl_outblk_14}]

# IP: bd/dma3/ip/dma3_blk_mem_gen_outblk_16/dma3_blk_mem_gen_outblk_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_blk_mem_gen_outblk_16 || ORIG_REF_NAME==dma3_blk_mem_gen_outblk_16}]

# IP: bd/dma3/ip/dma3_bmm_top_0_4/dma3_bmm_top_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_bmm_top_0_4 || ORIG_REF_NAME==dma3_bmm_top_0_4}]

# IP: bd/dma3/ip/dma3_bram_ctrl_in_blk_15/dma3_bram_ctrl_in_blk_15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_bram_ctrl_in_blk_15 || ORIG_REF_NAME==dma3_bram_ctrl_in_blk_15}]

# IP: bd/dma3/ip/dma3_blk_mem_gen_inblk_17/dma3_blk_mem_gen_inblk_17.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_blk_mem_gen_inblk_17 || ORIG_REF_NAME==dma3_blk_mem_gen_inblk_17}]

# IP: bd/dma3/ip/dma3_bram_ctrl_outblk_16/dma3_bram_ctrl_outblk_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_bram_ctrl_outblk_16 || ORIG_REF_NAME==dma3_bram_ctrl_outblk_16}]

# IP: bd/dma3/ip/dma3_blk_mem_gen_outblk_18/dma3_blk_mem_gen_outblk_18.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_blk_mem_gen_outblk_18 || ORIG_REF_NAME==dma3_blk_mem_gen_outblk_18}]

# IP: bd/dma3/ip/dma3_bram_ctrl_in_blk_17/dma3_bram_ctrl_in_blk_17.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_bram_ctrl_in_blk_17 || ORIG_REF_NAME==dma3_bram_ctrl_in_blk_17}]

# IP: bd/dma3/ip/dma3_blk_mem_gen_inblk_19/dma3_blk_mem_gen_inblk_19.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_blk_mem_gen_inblk_19 || ORIG_REF_NAME==dma3_blk_mem_gen_inblk_19}]

# IP: bd/dma3/ip/dma3_bram_ctrl_outblk_18/dma3_bram_ctrl_outblk_18.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_bram_ctrl_outblk_18 || ORIG_REF_NAME==dma3_bram_ctrl_outblk_18}]

# IP: bd/dma3/ip/dma3_blk_mem_gen_outblk_20/dma3_blk_mem_gen_outblk_20.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_blk_mem_gen_outblk_20 || ORIG_REF_NAME==dma3_blk_mem_gen_outblk_20}]

# IP: bd/dma3/ip/dma3_bram_ctrl_in_blk_19/dma3_bram_ctrl_in_blk_19.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_bram_ctrl_in_blk_19 || ORIG_REF_NAME==dma3_bram_ctrl_in_blk_19}]

# IP: bd/dma3/ip/dma3_blk_mem_gen_inblk_21/dma3_blk_mem_gen_inblk_21.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_blk_mem_gen_inblk_21 || ORIG_REF_NAME==dma3_blk_mem_gen_inblk_21}]

# IP: bd/dma3/ip/dma3_axi_interconnect_0_12/dma3_axi_interconnect_0_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_axi_interconnect_0_12 || ORIG_REF_NAME==dma3_axi_interconnect_0_12}]

# IP: bd/dma3/ip/dma3_xbar_10/dma3_xbar_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_xbar_10 || ORIG_REF_NAME==dma3_xbar_10}]

# IP: bd/dma3/ip/dma3_axi_interconnect_0_13/dma3_axi_interconnect_0_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_axi_interconnect_0_13 || ORIG_REF_NAME==dma3_axi_interconnect_0_13}]

# IP: bd/dma3/ip/dma3_xbar_11/dma3_xbar_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_xbar_11 || ORIG_REF_NAME==dma3_xbar_11}]

# IP: bd/dma3/ip/dma3_axi_interconnect_0_14/dma3_axi_interconnect_0_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_axi_interconnect_0_14 || ORIG_REF_NAME==dma3_axi_interconnect_0_14}]

# IP: bd/dma3/ip/dma3_xbar_12/dma3_xbar_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_xbar_12 || ORIG_REF_NAME==dma3_xbar_12}]

# IP: bd/dma3/ip/dma3_axi_dwidth_converter_0_1/dma3_axi_dwidth_converter_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_axi_dwidth_converter_0_1 || ORIG_REF_NAME==dma3_axi_dwidth_converter_0_1}]

# IP: bd/dma3/ip/dma3_axi_interconnect_1_15/dma3_axi_interconnect_1_15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_axi_interconnect_1_15 || ORIG_REF_NAME==dma3_axi_interconnect_1_15}]

# IP: bd/dma3/ip/dma3_xbar_13/dma3_xbar_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_xbar_13 || ORIG_REF_NAME==dma3_xbar_13}]

# IP: bd/dma3/ip/dma3_auto_pc_189/dma3_auto_pc_189.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_auto_pc_189 || ORIG_REF_NAME==dma3_auto_pc_189}]

# IP: bd/dma3/ip/dma3_auto_pc_190/dma3_auto_pc_190.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_auto_pc_190 || ORIG_REF_NAME==dma3_auto_pc_190}]

# IP: bd/dma3/ip/dma3_auto_pc_191/dma3_auto_pc_191.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_auto_pc_191 || ORIG_REF_NAME==dma3_auto_pc_191}]

# IP: bd/dma3/ip/dma3_auto_us_38/dma3_auto_us_38.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_auto_us_38 || ORIG_REF_NAME==dma3_auto_us_38}]

# IP: bd/dma3/ip/dma3_auto_us_39/dma3_auto_us_39.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_auto_us_39 || ORIG_REF_NAME==dma3_auto_us_39}]

# IP: bd/dma3/ip/dma3_auto_us_40/dma3_auto_us_40.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_auto_us_40 || ORIG_REF_NAME==dma3_auto_us_40}]

# IP: bd/dma3/ip/dma3_auto_us_41/dma3_auto_us_41.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_auto_us_41 || ORIG_REF_NAME==dma3_auto_us_41}]

# IP: bd/dma3/ip/dma3_auto_us_42/dma3_auto_us_42.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_auto_us_42 || ORIG_REF_NAME==dma3_auto_us_42}]

# IP: bd/dma3/ip/dma3_auto_us_43/dma3_auto_us_43.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_auto_us_43 || ORIG_REF_NAME==dma3_auto_us_43}]

# IP: bd/dma3/ip/dma3_auto_us_44/dma3_auto_us_44.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_auto_us_44 || ORIG_REF_NAME==dma3_auto_us_44}]

# IP: bd/dma3/ip/dma3_auto_us_45/dma3_auto_us_45.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_auto_us_45 || ORIG_REF_NAME==dma3_auto_us_45}]

# IP: bd/dma3/ip/dma3_auto_us_46/dma3_auto_us_46.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_auto_us_46 || ORIG_REF_NAME==dma3_auto_us_46}]

# IP: bd/dma3/ip/dma3_auto_us_47/dma3_auto_us_47.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_auto_us_47 || ORIG_REF_NAME==dma3_auto_us_47}]

# IP: bd/dma3/ip/dma3_auto_us_48/dma3_auto_us_48.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_auto_us_48 || ORIG_REF_NAME==dma3_auto_us_48}]

# IP: bd/dma3/ip/dma3_auto_us_49/dma3_auto_us_49.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma3_auto_us_49 || ORIG_REF_NAME==dma3_auto_us_49}]

# XDC: bd/dma3/ip/dma3_processing_system7_0_0/dma3_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma3_processing_system7_0_0 || ORIG_REF_NAME==dma3_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/dma3/ip/dma3_proc_sys_reset_1/dma3_proc_sys_reset_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma3_proc_sys_reset_1 || ORIG_REF_NAME==dma3_proc_sys_reset_1}] {/U0 }]/U0 ]]

# XDC: bd/dma3/ip/dma3_proc_sys_reset_1/dma3_proc_sys_reset_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma3_proc_sys_reset_1 || ORIG_REF_NAME==dma3_proc_sys_reset_1}] {/U0 }]/U0 ]]

# XDC: bd/dma3/ip/dma3_proc_sys_reset_1/dma3_proc_sys_reset_1_ooc.xdc

# XDC: bd/dma3/ip/dma3_axi_cdma_0_0/dma3_axi_cdma_0_0_ooc.xdc

# XDC: bd/dma3/ip/dma3_axi_cdma_0_0/dma3_axi_cdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma3_axi_cdma_0_0 || ORIG_REF_NAME==dma3_axi_cdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/dma3/ip/dma3_xbar_1/dma3_xbar_1_ooc.xdc

# XDC: bd/dma3/ip/dma3_xbar_2/dma3_xbar_2_ooc.xdc

# XDC: bd/dma3/ip/dma3_fe_top_0_0/constraints/fe_top_ooc.xdc

# XDC: bd/dma3/ip/dma3_bmm_top_0_1/constraints/bmm_top_ooc.xdc

# XDC: bd/dma3/ip/dma3_bmm_top_0_2/constraints/bmm_top_ooc.xdc

# XDC: bd/dma3/ip/dma3_bram_ctrl_in_blk_10/dma3_bram_ctrl_in_blk_10_ooc.xdc

# XDC: bd/dma3/ip/dma3_blk_mem_gen_inblk_12/dma3_blk_mem_gen_inblk_12_ooc.xdc

# XDC: bd/dma3/ip/dma3_bram_ctrl_outblk_11/dma3_bram_ctrl_outblk_11_ooc.xdc

# XDC: bd/dma3/ip/dma3_blk_mem_gen_outblk_13/dma3_blk_mem_gen_outblk_13_ooc.xdc

# XDC: bd/dma3/ip/dma3_bmm_top_0_3/constraints/bmm_top_ooc.xdc

# XDC: bd/dma3/ip/dma3_bram_ctrl_in_blk_13/dma3_bram_ctrl_in_blk_13_ooc.xdc

# XDC: bd/dma3/ip/dma3_blk_mem_gen_inblk_15/dma3_blk_mem_gen_inblk_15_ooc.xdc

# XDC: bd/dma3/ip/dma3_bram_ctrl_outblk_14/dma3_bram_ctrl_outblk_14_ooc.xdc

# XDC: bd/dma3/ip/dma3_blk_mem_gen_outblk_16/dma3_blk_mem_gen_outblk_16_ooc.xdc

# XDC: bd/dma3/ip/dma3_bmm_top_0_4/constraints/bmm_top_ooc.xdc

# XDC: bd/dma3/ip/dma3_bram_ctrl_in_blk_15/dma3_bram_ctrl_in_blk_15_ooc.xdc

# XDC: bd/dma3/ip/dma3_blk_mem_gen_inblk_17/dma3_blk_mem_gen_inblk_17_ooc.xdc

# XDC: bd/dma3/ip/dma3_bram_ctrl_outblk_16/dma3_bram_ctrl_outblk_16_ooc.xdc

# XDC: bd/dma3/ip/dma3_blk_mem_gen_outblk_18/dma3_blk_mem_gen_outblk_18_ooc.xdc

# XDC: bd/dma3/ip/dma3_bram_ctrl_in_blk_17/dma3_bram_ctrl_in_blk_17_ooc.xdc

# XDC: bd/dma3/ip/dma3_blk_mem_gen_inblk_19/dma3_blk_mem_gen_inblk_19_ooc.xdc

# XDC: bd/dma3/ip/dma3_bram_ctrl_outblk_18/dma3_bram_ctrl_outblk_18_ooc.xdc

# XDC: bd/dma3/ip/dma3_blk_mem_gen_outblk_20/dma3_blk_mem_gen_outblk_20_ooc.xdc

# XDC: bd/dma3/ip/dma3_bram_ctrl_in_blk_19/dma3_bram_ctrl_in_blk_19_ooc.xdc

# XDC: bd/dma3/ip/dma3_blk_mem_gen_inblk_21/dma3_blk_mem_gen_inblk_21_ooc.xdc

# XDC: bd/dma3/ip/dma3_xbar_10/dma3_xbar_10_ooc.xdc

# XDC: bd/dma3/ip/dma3_xbar_11/dma3_xbar_11_ooc.xdc

# XDC: bd/dma3/ip/dma3_xbar_12/dma3_xbar_12_ooc.xdc

# XDC: bd/dma3/ip/dma3_axi_dwidth_converter_0_1/dma3_axi_dwidth_converter_0_1_ooc.xdc

# XDC: bd/dma3/ip/dma3_axi_dwidth_converter_0_1/dma3_axi_dwidth_converter_0_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma3_axi_dwidth_converter_0_1 || ORIG_REF_NAME==dma3_axi_dwidth_converter_0_1}] {/inst }]/inst ]]

# XDC: bd/dma3/ip/dma3_xbar_13/dma3_xbar_13_ooc.xdc

# XDC: bd/dma3/ip/dma3_auto_pc_189/dma3_auto_pc_189_ooc.xdc

# XDC: bd/dma3/ip/dma3_auto_pc_190/dma3_auto_pc_190_ooc.xdc

# XDC: bd/dma3/ip/dma3_auto_pc_191/dma3_auto_pc_191_ooc.xdc

# XDC: bd/dma3/ip/dma3_auto_us_38/dma3_auto_us_38_ooc.xdc

# XDC: bd/dma3/ip/dma3_auto_us_38/dma3_auto_us_38_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma3_auto_us_38 || ORIG_REF_NAME==dma3_auto_us_38}] {/inst }]/inst ]]

# XDC: bd/dma3/ip/dma3_auto_us_39/dma3_auto_us_39_ooc.xdc

# XDC: bd/dma3/ip/dma3_auto_us_39/dma3_auto_us_39_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma3_auto_us_39 || ORIG_REF_NAME==dma3_auto_us_39}] {/inst }]/inst ]]

# XDC: bd/dma3/ip/dma3_auto_us_40/dma3_auto_us_40_ooc.xdc

# XDC: bd/dma3/ip/dma3_auto_us_40/dma3_auto_us_40_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma3_auto_us_40 || ORIG_REF_NAME==dma3_auto_us_40}] {/inst }]/inst ]]

# XDC: bd/dma3/ip/dma3_auto_us_41/dma3_auto_us_41_ooc.xdc

# XDC: bd/dma3/ip/dma3_auto_us_41/dma3_auto_us_41_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma3_auto_us_41 || ORIG_REF_NAME==dma3_auto_us_41}] {/inst }]/inst ]]

# XDC: bd/dma3/ip/dma3_auto_us_42/dma3_auto_us_42_ooc.xdc

# XDC: bd/dma3/ip/dma3_auto_us_42/dma3_auto_us_42_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma3_auto_us_42 || ORIG_REF_NAME==dma3_auto_us_42}] {/inst }]/inst ]]

# XDC: bd/dma3/ip/dma3_auto_us_43/dma3_auto_us_43_ooc.xdc

# XDC: bd/dma3/ip/dma3_auto_us_43/dma3_auto_us_43_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma3_auto_us_43 || ORIG_REF_NAME==dma3_auto_us_43}] {/inst }]/inst ]]

# XDC: bd/dma3/ip/dma3_auto_us_44/dma3_auto_us_44_ooc.xdc

# XDC: bd/dma3/ip/dma3_auto_us_44/dma3_auto_us_44_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma3_auto_us_44 || ORIG_REF_NAME==dma3_auto_us_44}] {/inst }]/inst ]]

# XDC: bd/dma3/ip/dma3_auto_us_45/dma3_auto_us_45_ooc.xdc

# XDC: bd/dma3/ip/dma3_auto_us_45/dma3_auto_us_45_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma3_auto_us_45 || ORIG_REF_NAME==dma3_auto_us_45}] {/inst }]/inst ]]

# XDC: bd/dma3/ip/dma3_auto_us_46/dma3_auto_us_46_ooc.xdc

# XDC: bd/dma3/ip/dma3_auto_us_46/dma3_auto_us_46_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma3_auto_us_46 || ORIG_REF_NAME==dma3_auto_us_46}] {/inst }]/inst ]]

# XDC: bd/dma3/ip/dma3_auto_us_47/dma3_auto_us_47_ooc.xdc

# XDC: bd/dma3/ip/dma3_auto_us_47/dma3_auto_us_47_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma3_auto_us_47 || ORIG_REF_NAME==dma3_auto_us_47}] {/inst }]/inst ]]

# XDC: bd/dma3/ip/dma3_auto_us_48/dma3_auto_us_48_ooc.xdc

# XDC: bd/dma3/ip/dma3_auto_us_48/dma3_auto_us_48_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma3_auto_us_48 || ORIG_REF_NAME==dma3_auto_us_48}] {/inst }]/inst ]]

# XDC: bd/dma3/ip/dma3_auto_us_49/dma3_auto_us_49_ooc.xdc

# XDC: bd/dma3/ip/dma3_auto_us_49/dma3_auto_us_49_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==dma3_auto_us_49 || ORIG_REF_NAME==dma3_auto_us_49}] {/inst }]/inst ]]

# XDC: bd/dma3/dma3_ooc.xdc
