// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xsimple_top.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XSimple_top_CfgInitialize(XSimple_top *InstancePtr, XSimple_top_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_BaseAddress = ConfigPtr->Control_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XSimple_top_Start(XSimple_top *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSimple_top_ReadReg(InstancePtr->Control_BaseAddress, XSIMPLE_TOP_CONTROL_ADDR_AP_CTRL) & 0x80;
    XSimple_top_WriteReg(InstancePtr->Control_BaseAddress, XSIMPLE_TOP_CONTROL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XSimple_top_IsDone(XSimple_top *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSimple_top_ReadReg(InstancePtr->Control_BaseAddress, XSIMPLE_TOP_CONTROL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XSimple_top_IsIdle(XSimple_top *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSimple_top_ReadReg(InstancePtr->Control_BaseAddress, XSIMPLE_TOP_CONTROL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XSimple_top_IsReady(XSimple_top *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSimple_top_ReadReg(InstancePtr->Control_BaseAddress, XSIMPLE_TOP_CONTROL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XSimple_top_EnableAutoRestart(XSimple_top *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSimple_top_WriteReg(InstancePtr->Control_BaseAddress, XSIMPLE_TOP_CONTROL_ADDR_AP_CTRL, 0x80);
}

void XSimple_top_DisableAutoRestart(XSimple_top *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSimple_top_WriteReg(InstancePtr->Control_BaseAddress, XSIMPLE_TOP_CONTROL_ADDR_AP_CTRL, 0);
}

void XSimple_top_InterruptGlobalEnable(XSimple_top *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSimple_top_WriteReg(InstancePtr->Control_BaseAddress, XSIMPLE_TOP_CONTROL_ADDR_GIE, 1);
}

void XSimple_top_InterruptGlobalDisable(XSimple_top *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSimple_top_WriteReg(InstancePtr->Control_BaseAddress, XSIMPLE_TOP_CONTROL_ADDR_GIE, 0);
}

void XSimple_top_InterruptEnable(XSimple_top *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XSimple_top_ReadReg(InstancePtr->Control_BaseAddress, XSIMPLE_TOP_CONTROL_ADDR_IER);
    XSimple_top_WriteReg(InstancePtr->Control_BaseAddress, XSIMPLE_TOP_CONTROL_ADDR_IER, Register | Mask);
}

void XSimple_top_InterruptDisable(XSimple_top *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XSimple_top_ReadReg(InstancePtr->Control_BaseAddress, XSIMPLE_TOP_CONTROL_ADDR_IER);
    XSimple_top_WriteReg(InstancePtr->Control_BaseAddress, XSIMPLE_TOP_CONTROL_ADDR_IER, Register & (~Mask));
}

void XSimple_top_InterruptClear(XSimple_top *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSimple_top_WriteReg(InstancePtr->Control_BaseAddress, XSIMPLE_TOP_CONTROL_ADDR_ISR, Mask);
}

u32 XSimple_top_InterruptGetEnabled(XSimple_top *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSimple_top_ReadReg(InstancePtr->Control_BaseAddress, XSIMPLE_TOP_CONTROL_ADDR_IER);
}

u32 XSimple_top_InterruptGetStatus(XSimple_top *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XSimple_top_ReadReg(InstancePtr->Control_BaseAddress, XSIMPLE_TOP_CONTROL_ADDR_ISR);
}

